name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        path: src/github.com/containerd/project
        fetch-depth: 25

    - uses: containerd/project-checks@v1.2.2
      with:
        working-directory: src/github.com/containerd/project
